// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	script_name: "file";
	API_TOKEN: string;
	account_id: string;
	email: string;
	token: string;
	DB: D1Database;
	store: Fetcher;
}
