#:schema node_modules/wrangler/config-schema.json
name = "edgestore"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "edgestore"
database_id = "da3bcf3e-34ab-4a43-987b-01de6b7ceb65"

[[services]]
binding = "store"
service = "file"

[vars]
script_name = "file"
